# This is a basic workflow to help you get started with Actions

name: demo github actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "devops-simple-node1" branch
  push:
    branches: [ "devops-simple-node1" ]
  pull_request:
    branches: [ "devops-simple-node1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY : ${{ secrets.DOCKER_USERNAME }}
  REPOSITORY: ${{github.event.repository.name}}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 21
      - name: instalar dependencias
        run: npm install
      - name: Ejecutar test
        run: npm run test

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest,
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}
          
