
name: demo github actions

on:
  push:
    branches: [ "devops-simple-node1" ]
  pull_request:
    branches: [ "devops-simple-node1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REGISTRY : ${{ secrets.DOCKER_USERNAME }}
  REPOSITORY: ${{github.event.repository.name}}
jobs:
  init:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 21
      - name: instalar dependencias
        run: npm install

  test:
    needs: init
    name: Test 🦠
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 21
      - name: Run test
        run: npm run test
        
  deploy_to_dev:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: test
c
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest,
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}
          
  deploy_to_prd:
    name: Deploy to prod
    runs-on: ubuntu-latest
    needs: test
    environment: 
      name: prod
      url: demo.codigofacilito.com
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:latest,
            ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ github.sha }}
